version: 2
jobs:
  example:
    docker:
      (略)
      - image: amazon/dynamodb-local
        ports:
          - 8000:8000
          
    steps:
      (略)
      - run:
          name: Create DynamoDB Table
          command: AWS_ACCESS_KEY_ID=ABCDXXXXXXXXXXXXABCD AWS_SECRET_ACCESS_KEY=ABCDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXABCD  AWS_DEFAULT_REGION=ap-northeast-1 aws --endpoint-url http://127.0.0.1:8000 dynamodb create-table --table-name example-table ...(略)
